In [2]:
import pandas as pd
import numpy as np
import re
from datetime import datetime
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string
import re

**Importing all the necessary libraries**

In [3]:
df = pd.read_csv(r"C:\Users\Fateh\Documents\FYP_SENTIMENT_ANALYSIS\Data_Collection\Raw_Data\Reddit_raw.csv\comments.csv\comments.csv", low_memory=False)

**Reddit Dataset**

In [4]:
df.head()

,author,body,date,id,parentId,subreddit,url
0,Away-Sleep-2010,"Hi, Zerobeat, you can ask ChatGPT by copying a...",2023-05-01 17:02:02+00:00,t1_jigaps4,42474156065.0,CharacterAI_No_Filter,https://old.reddit.com/r/CharacterAI_No_Filter...
1,d3str0yer,Da ist dann auch nicht ChatGPT das Problem son...,2023-05-01 17:01:55+00:00,t1_jigap4v,42474453636.0,FragReddit,https://old.reddit.com/r/FragReddit/comments/1...
2,gbchrome,"That’d probably be my luck, being falsely accu...",2023-05-01 17:01:24+00:00,t1_jigamdl,42472193724.0,LifeProTips,https://old.reddit.com/r/LifeProTips/comments/...
3,dreamwall,ChatGPT and Bing didn't helped that much. Chat...,2023-05-01 17:01:16+00:00,t1_jigalkq,NaN,tipofmytongue,https://old.reddit.com/r/tipofmytongue/comment...
4,tundey_1,What straws? That you have to train people bef...,2023-05-01 17:01:07+00:00,t1_jigakso,42474444199.0,technology,https://old.reddit.com/r/technology/comments/1...

In [5]:
print(df["body"].iloc[131])

Which means halting AI development and placing artificial limits on how useful it can be.

Also many plugins for ChatGPT can send emails. There's also chaosGPT which created its own Twitter in its attempt to gain power and end mankind.

(It was unsuccessful in its attempt).

The point is, an entity smarter than humans can likely utilise mechanisms not thought of by humans to achieve goals not understood by humans.

It's what they call an unknown unknown.

In [6]:
df.describe

<bound method NDFrame.describe of                   author                                               body  \
0        Away-Sleep-2010  Hi, Zerobeat, you can ask ChatGPT by copying a...
1              d3str0yer  Da ist dann auch nicht ChatGPT das Problem son...
2               gbchrome  That’d probably be my luck, being falsely accu...
3              dreamwall  ChatGPT and Bing didn't helped that much. Chat...
4               tundey_1  What straws? That you have to train people bef...
...                  ...                                                ...
1033631         odonnthe  Er. \n\nAll “AI” is “big data analysis”. Every...
1033632          Sammx26  I dont work in IT but this sort of thing freak...
1033633          Telewyn  It’s an emulator, not a native program.  Not a...
1033634         googs185  I’m thinking of getting a data science or arti...
1033635           d0s4gw  Artificial general intelligence, artificial su...

                              date          id       parentId  \
0        2023-05-01 17:02:02+00:00  t1_jigaps4  42474156065.0
1        2023-05-01 17:01:55+00:00  t1_jigap4v  42474453636.0
2        2023-05-01 17:01:24+00:00  t1_jigamdl  42472193724.0
3        2023-05-01 17:01:16+00:00  t1_jigalkq            NaN
4        2023-05-01 17:01:07+00:00  t1_jigakso  42474444199.0
...                            ...         ...            ...
1033631  2021-10-31 00:42:47+00:00  t1_hipkgz5  38135992250.0
1033632  2021-10-31 00:31:45+00:00  t1_hipj4rb  38132173665.0
1033633  2021-10-31 00:12:57+00:00  t1_hipgw5m  38136368748.0
1033634  2021-10-30 23:55:54+00:00  t1_hipew1t  38135316480.0
1033635  2021-10-30 23:51:51+00:00  t1_hipees8  38131810789.0

                     subreddit  \
0        CharacterAI_No_Filter
1                   FragReddit
2                  LifeProTips
3                tipofmytongue
4                   technology
...                        ...
1033631              samharris
1033632                    LSD
1033633      AskScienceFiction
1033634                fatFIRE
1033635            singularity

                                                       url
0        https://old.reddit.com/r/CharacterAI_No_Filter...
1        https://old.reddit.com/r/FragReddit/comments/1...
2        https://old.reddit.com/r/LifeProTips/comments/...
3        https://old.reddit.com/r/tipofmytongue/comment...
4        https://old.reddit.com/r/technology/comments/1...
...                                                    ...
1033631  https://old.reddit.com/r/samharris/comments/qj...
1033632  https://old.reddit.com/r/LSD/comments/qiykp7/i...
1033633  https://old.reddit.com/r/AskScienceFiction/com...
1033634  https://old.reddit.com/r/fatFIRE/comments/qj7d...
1033635  https://old.reddit.com/r/singularity/comments/...

[1033636 rows x 7 columns]>

In [7]:
df.index

RangeIndex(start=0, stop=1033636, step=1)

In [8]:
df.columns

Index(['author', 'body', 'date', 'id', 'parentId', 'subreddit', 'url'], dtype='object')

In [9]:
Keywords = ["Generative AI", "GenAI", "Artificial Intelligence", "AI"]

In [10]:
Keywords_pattern = ' | '.join(Keywords)

In [11]:
Keyword_pattern = "The_search_term"

In [12]:
print(Keywords_pattern)

Generative AI | GenAI | Artificial Intelligence | AI

In [13]:
Filtered_df = df[df["body"].str.lower().str.contains(Keyword_pattern, na=False)]
print(Filtered_df)

Empty DataFrame
Columns: [author, body, date, id, parentId, subreddit, url]
Index: []

In [14]:
Filtered_df.columns

Index(['author', 'body', 'date', 'id', 'parentId', 'subreddit', 'url'], dtype='object')

In [15]:
df.drop(['author', 'id', 'parentId', 'subreddit', 'url'], axis=1, inplace=True)

In [16]:
keywords = ["generative ai", "genai", "artificial intelligence", "ai"]

pattern = "|".join(keywords)

filtered_df = df[
    df["body"].str.lower().str.contains(pattern, na=False)
]

print("Filtered rows:", len(filtered_df))

Filtered rows: 711462

In [17]:
print(filtered_df)

                                                      body  \
4        What straws? That you have to train people bef...
5        heres an answer from chatgpt\n\n&amp;#x200B;\n...
11       Missing the whole body of the argument and gra...
12       Thank you for your input!\n\nI just started a ...
13       Hey /u/cstein123, please respond to this comme...
...                                                    ...
1033630  Artificial General Intelligence - an AI that c...
1033631  Er. \n\nAll “AI” is “big data analysis”. Every...
1033632  I dont work in IT but this sort of thing freak...
1033633  It’s an emulator, not a native program.  Not a...
1033634  I’m thinking of getting a data science or arti...

                              date
4        2023-05-01 17:01:07+00:00
5        2023-05-01 17:00:57+00:00
11       2023-05-01 16:59:43+00:00
12       2023-05-01 16:59:43+00:00
13       2023-05-01 16:59:32+00:00
...                            ...
1033630  2021-10-31 00:48:33+00:00
1033631  2021-10-31 00:42:47+00:00
1033632  2021-10-31 00:31:45+00:00
1033633  2021-10-31 00:12:57+00:00
1033634  2021-10-30 23:55:54+00:00

[711462 rows x 2 columns]

In [18]:
filtered_df.columns

Index(['body', 'date'], dtype='object')

In [19]:
filtered_df['date']

4          2023-05-01 17:01:07+00:00
5          2023-05-01 17:00:57+00:00
11         2023-05-01 16:59:43+00:00
12         2023-05-01 16:59:43+00:00
13         2023-05-01 16:59:32+00:00
                     ...
1033630    2021-10-31 00:48:33+00:00
1033631    2021-10-31 00:42:47+00:00
1033632    2021-10-31 00:31:45+00:00
1033633    2021-10-31 00:12:57+00:00
1033634    2021-10-30 23:55:54+00:00
Name: date, Length: 711462, dtype: object

In [20]:
filtered_df.columns

Index(['body', 'date'], dtype='object')

In [21]:
filtered_df

,body,date
4,What straws? That you have to train people bef...,2023-05-01 17:01:07+00:00
5,heres an answer from chatgpt\n\n&amp;#x200B;\n...,2023-05-01 17:00:57+00:00
11,Missing the whole body of the argument and gra...,2023-05-01 16:59:43+00:00
12,Thank you for your input!\n\nI just started a ...,2023-05-01 16:59:43+00:00
13,"Hey /u/cstein123, please respond to this comme...",2023-05-01 16:59:32+00:00
...,...,...
1033630,Artificial General Intelligence - an AI that c...,2021-10-31 00:48:33+00:00
1033631,Er. \n\nAll “AI” is “big data analysis”. Every...,2021-10-31 00:42:47+00:00
1033632,I dont work in IT but this sort of thing freak...,2021-10-31 00:31:45+00:00
1033633,"It’s an emulator, not a native program. Not a...",2021-10-31 00:12:57+00:00
1033634,I’m thinking of getting a data science or arti...,2021-10-30 23:55:54+00:00

In [22]:
filtered_df.columns

Index(['body', 'date'], dtype='object')

In [23]:
print(filtered_df)

                                                      body  \
4        What straws? That you have to train people bef...
5        heres an answer from chatgpt\n\n&amp;#x200B;\n...
11       Missing the whole body of the argument and gra...
12       Thank you for your input!\n\nI just started a ...
13       Hey /u/cstein123, please respond to this comme...
...                                                    ...
1033630  Artificial General Intelligence - an AI that c...
1033631  Er. \n\nAll “AI” is “big data analysis”. Every...
1033632  I dont work in IT but this sort of thing freak...
1033633  It’s an emulator, not a native program.  Not a...
1033634  I’m thinking of getting a data science or arti...

                              date
4        2023-05-01 17:01:07+00:00
5        2023-05-01 17:00:57+00:00
11       2023-05-01 16:59:43+00:00
12       2023-05-01 16:59:43+00:00
13       2023-05-01 16:59:32+00:00
...                            ...
1033630  2021-10-31 00:48:33+00:00
1033631  2021-10-31 00:42:47+00:00
1033632  2021-10-31 00:31:45+00:00
1033633  2021-10-31 00:12:57+00:00
1033634  2021-10-30 23:55:54+00:00

[711462 rows x 2 columns]

In [24]:
filtered_df.columns

Index(['body', 'date'], dtype='object')

In [25]:
filtered_df

,body,date
4,What straws? That you have to train people bef...,2023-05-01 17:01:07+00:00
5,heres an answer from chatgpt\n\n&amp;#x200B;\n...,2023-05-01 17:00:57+00:00
11,Missing the whole body of the argument and gra...,2023-05-01 16:59:43+00:00
12,Thank you for your input!\n\nI just started a ...,2023-05-01 16:59:43+00:00
13,"Hey /u/cstein123, please respond to this comme...",2023-05-01 16:59:32+00:00
...,...,...
1033630,Artificial General Intelligence - an AI that c...,2021-10-31 00:48:33+00:00
1033631,Er. \n\nAll “AI” is “big data analysis”. Every...,2021-10-31 00:42:47+00:00
1033632,I dont work in IT but this sort of thing freak...,2021-10-31 00:31:45+00:00
1033633,"It’s an emulator, not a native program. Not a...",2021-10-31 00:12:57+00:00
1033634,I’m thinking of getting a data science or arti...,2021-10-30 23:55:54+00:00

**Identifying the keywords and starting the cleaning process**

In [26]:
keyword_pattern = ["generative ai", "genai", "artificial intelligence", "ai"]

pattern = "|".join(keyword_pattern)

filtered_df = df[
    df["body"].str.lower().str.contains(pattern, na=False)
]

print("Filtered rows:", len(filtered_df))

Filtered rows: 711462

In [27]:
filtered_df = df[
    df["body"]
    .str.lower()
    .str.contains(pattern, na=False)
]

In [28]:
filtered_df

,body,date
4,What straws? That you have to train people bef...,2023-05-01 17:01:07+00:00
5,heres an answer from chatgpt\n\n&amp;#x200B;\n...,2023-05-01 17:00:57+00:00
11,Missing the whole body of the argument and gra...,2023-05-01 16:59:43+00:00
12,Thank you for your input!\n\nI just started a ...,2023-05-01 16:59:43+00:00
13,"Hey /u/cstein123, please respond to this comme...",2023-05-01 16:59:32+00:00
...,...,...
1033630,Artificial General Intelligence - an AI that c...,2021-10-31 00:48:33+00:00
1033631,Er. \n\nAll “AI” is “big data analysis”. Every...,2021-10-31 00:42:47+00:00
1033632,I dont work in IT but this sort of thing freak...,2021-10-31 00:31:45+00:00
1033633,"It’s an emulator, not a native program. Not a...",2021-10-31 00:12:57+00:00
1033634,I’m thinking of getting a data science or arti...,2021-10-30 23:55:54+00:00

In [29]:
filtered_df.shape

(711462, 2)

In [30]:
filtered_df.isna().sum()

body    0
date    4
dtype: int64

In [31]:
filtered_df.dropna()

,body,date
4,What straws? That you have to train people bef...,2023-05-01 17:01:07+00:00
5,heres an answer from chatgpt\n\n&amp;#x200B;\n...,2023-05-01 17:00:57+00:00
11,Missing the whole body of the argument and gra...,2023-05-01 16:59:43+00:00
12,Thank you for your input!\n\nI just started a ...,2023-05-01 16:59:43+00:00
13,"Hey /u/cstein123, please respond to this comme...",2023-05-01 16:59:32+00:00
...,...,...
1033630,Artificial General Intelligence - an AI that c...,2021-10-31 00:48:33+00:00
1033631,Er. \n\nAll “AI” is “big data analysis”. Every...,2021-10-31 00:42:47+00:00
1033632,I dont work in IT but this sort of thing freak...,2021-10-31 00:31:45+00:00
1033633,"It’s an emulator, not a native program. Not a...",2021-10-31 00:12:57+00:00
1033634,I’m thinking of getting a data science or arti...,2021-10-30 23:55:54+00:00

In [32]:
filtered_df.isna().sum()

body    0
date    4
dtype: int64

In [33]:
filtered_df.isna().value_counts(['date'])

date
False    711458
True          4
Name: count, dtype: int64

In [34]:
filtered_df['date'] = pd.to_datetime(filtered_df['date'])

C:\Users\Fateh\AppData\Local\Temp\ipykernel_28580\1121199746.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['date'] = pd.to_datetime(filtered_df['date'])

In [35]:
filtered_df['body'] = filtered_df['body'].str.replace(r'[^\w\s]', ' ', regex=True)

C:\Users\Fateh\AppData\Local\Temp\ipykernel_28580\1689529248.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['body'] = filtered_df['body'].str.replace(r'[^\w\s]', ' ', regex=True)

In [36]:
filtered_df.body

4          What straws  That you have to train people bef...
5          heres an answer from chatgpt\n\n amp  x200B \n...
11         Missing the whole body of the argument and gra...
12         Thank you for your input \n\nI just started a ...
13         Hey  u cstein123  please respond to this comme...
                                 ...
1033630    Artificial General Intelligence   an AI that c...
1033631    Er  \n\nAll  AI  is  big data analysis   Every...
1033632    I dont work in IT but this sort of thing freak...
1033633    It s an emulator  not a native program   Not a...
1033634    I m thinking of getting a data science or arti...
Name: body, Length: 711462, dtype: object

**Preparing the data for the analysis**

In [37]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string
from nltk.sentiment import SentimentIntensityAnalyzer
import torch
import warnings 
warnings.filterwarnings('ignore')

In [38]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Fateh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Fateh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Fateh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Fateh\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

**Initialising the stopwords and the lemmatizer**

In [39]:
stop_word = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

**Cleaning the text data of the body column**

In [40]:
def clean_text(text):

   import nltk
   from nltk.stem import WordNetLemmatizer
   from nltk.corpus import stopwords
   from nltk.tokenize import word_tokenize
   import string
   import re



   stop_word = set(stopwords.words('english'))


    
   text = text.lower()
   text = str(text)
     
    
   text = re.sub(r"can't", "cannot", text)
   text = re.sub(r"n't", " not", text)
   text = re.sub(r"'d", " would", text)
   text = re.sub(r"'re", " are", text)
   text = re.sub(r"ll", " will", text)
   text = re.sub(r"won't", "will not", text)
   text = re.sub(r"'ve", " have", text)
   text = re.sub(r"'m", " am", text)
    
   text = re.sub(r'\s+',  ' ', text).strip()


   #removing url's, hashtags, and mentoins
   text = re.sub(r"#", "", text)
   text = re.sub(r"http\S+|www\S+", "", text)
   text = re.sub(r"@\w+", "", text)

   #Tokenising the text of the body column
   token = word_tokenize(text)
   # Lemmatization process
   lemmatizer = WordNetLemmatizer()
   The_clean_tokens = [lemmatizer.lemmatize(word) for word in token if word not in stop_word]
   The_cleaned_text = ' '.join(The_clean_tokens)

   return " ".join(The_clean_tokens)

In [41]:
sample_text = "I can't believe it's working! You're amazing and I'll be there soon."
cleaned = clean_text(sample_text)
print(cleaned)

believe 's working ! amazing ' soon .

In [42]:
filtered_df.body

4          What straws  That you have to train people bef...
5          heres an answer from chatgpt\n\n amp  x200B \n...
11         Missing the whole body of the argument and gra...
12         Thank you for your input \n\nI just started a ...
13         Hey  u cstein123  please respond to this comme...
                                 ...
1033630    Artificial General Intelligence   an AI that c...
1033631    Er  \n\nAll  AI  is  big data analysis   Every...
1033632    I dont work in IT but this sort of thing freak...
1033633    It s an emulator  not a native program   Not a...
1033634    I m thinking of getting a data science or arti...
Name: body, Length: 711462, dtype: object

In [43]:
filtered_df.columns

Index(['body', 'date'], dtype='object')

In [44]:
filtered_df["cleaned_text"] = (
    filtered_df["body"]
    .fillna("")
    .apply(clean_text)
)

In [45]:
filtered_df.columns

Index(['body', 'date', 'cleaned_text'], dtype='object')

In [46]:
filtered_df

,body,date,cleaned_text
4,What straws That you have to train people bef...,2023-05-01 17:01:07+00:00,straw train people give access new tool mean s...
5,heres an answer from chatgpt\n\n amp x200B \n...,2023-05-01 17:00:57+00:00,here answer chatgpt amp x200b gt chatgpt ultim...
11,Missing the whole body of the argument and gra...,2023-05-01 16:59:43+00:00,missing whole body argument grabbing onto sing...
12,Thank you for your input \n\nI just started a ...,2023-05-01 16:59:43+00:00,thank input started post grad using lot since ...
13,Hey u cstein123 please respond to this comme...,2023-05-01 16:59:32+00:00,hey u cstein123 please respond comment prompt ...
...,...,...,...
1033630,Artificial General Intelligence an AI that c...,2021-10-31 00:48:33+00:00,artificial general inte willigence ai think re...
1033631,Er \n\nAll AI is big data analysis Every...,2021-10-31 00:42:47+00:00,er ai big data analysis everything currently c...
1033632,I dont work in IT but this sort of thing freak...,2021-10-31 00:31:45+00:00,dont work sort thing freak thing happening wor...
1033633,It s an emulator not a native program Not a...,2021-10-31 00:12:57+00:00,emulator native program true artificial inte w...
1033634,I m thinking of getting a data science or arti...,2021-10-30 23:55:54+00:00,thinking getting data science artificial inte ...

In [47]:
Posts_from_2023 = filtered_df[filtered_df['date'].dt.year == 2023]

In [48]:
print(f"Total posts from 2023: {len(Posts_from_2023)}")

Total posts from 2023: 523017

**Picking 500 random posts from the dataset**

In [49]:
finalised_df = Posts_from_2023.sample(n=500, random_state=42)

In [50]:
len(finalised_df)

500

In [51]:
year_counts = finalised_df['date'].dt.year.value_counts().sort_index()

In [52]:
year_counts

date
2023    500
Name: count, dtype: int64

In [53]:
len(finalised_df)

500

In [54]:
finalised_df.to_csv('Reddit_cleaned.csv', index=False)

**Implementing the VADER Sentiment Analysis Model**

In [55]:
pip install vaderSentiment

Requirement already satisfied: vaderSentiment in c:\users\fateh\anaconda3\lib\site-packages (3.3.2)
Requirement already satisfied: requests in c:\users\fateh\anaconda3\lib\site-packages (from vaderSentiment) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\fateh\anaconda3\lib\site-packages (from requests->vaderSentiment) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\fateh\anaconda3\lib\site-packages (from requests->vaderSentiment) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\fateh\anaconda3\lib\site-packages (from requests->vaderSentiment) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\fateh\anaconda3\lib\site-packages (from requests->vaderSentiment) (2025.4.26)
Note: you may need to restart the kernel to use updated packages.

In [56]:
pip install transformers[torch]

Requirement already satisfied: transformers[torch] in c:\users\fateh\anaconda3\lib\site-packages (4.57.6)
Requirement already satisfied: filelock in c:\users\fateh\anaconda3\lib\site-packages (from transformers[torch]) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in c:\users\fateh\anaconda3\lib\site-packages (from transformers[torch]) (0.36.0)
Requirement already satisfied: numpy>=1.17 in c:\users\fateh\anaconda3\lib\site-packages (from transformers[torch]) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\fateh\anaconda3\lib\site-packages (from transformers[torch]) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\fateh\anaconda3\lib\site-packages (from transformers[torch]) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in c:\users\fateh\anaconda3\lib\site-packages (from transformers[torch]) (2024.9.11)
Requirement already satisfied: requests in c:\users\fateh\anaconda3\lib\site-packages (from transformers[torch]) (2.32.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\fateh\anaconda3\lib\site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\fateh\anaconda3\lib\site-packages (from transformers[torch]) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\fateh\anaconda3\lib\site-packages (from transformers[torch]) (4.66.5)
Requirement already satisfied: torch>=2.2 in c:\users\fateh\anaconda3\lib\site-packages (from transformers[torch]) (2.9.1)
Requirement already satisfied: accelerate>=0.26.0 in c:\users\fateh\anaconda3\lib\site-packages (from transformers[torch]) (1.12.0)
Requirement already satisfied: psutil in c:\users\fateh\anaconda3\lib\site-packages (from accelerate>=0.26.0->transformers[torch]) (5.9.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\fateh\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers[torch]) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\fateh\anaconda3\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers[torch]) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\fateh\anaconda3\lib\site-packages (from torch>=2.2->transformers[torch]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\fateh\anaconda3\lib\site-packages (from torch>=2.2->transformers[torch]) (3.3)
Requirement already satisfied: jinja2 in c:\users\fateh\anaconda3\lib\site-packages (from torch>=2.2->transformers[torch]) (3.1.4)
Requirement already satisfied: setuptools in c:\users\fateh\anaconda3\lib\site-packages (from torch>=2.2->transformers[torch]) (75.1.0)
Requirement already satisfied: colorama in c:\users\fateh\anaconda3\lib\site-packages (from tqdm>=4.27->transformers[torch]) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\fateh\anaconda3\lib\site-packages (from requests->transformers[torch]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\fateh\anaconda3\lib\site-packages (from requests->transformers[torch]) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\fateh\anaconda3\lib\site-packages (from requests->transformers[torch]) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\fateh\anaconda3\lib\site-packages (from requests->transformers[torch]) (2025.4.26)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\fateh\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.2->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\fateh\anaconda3\lib\site-packages (from jinja2->torch>=2.2->transformers[torch]) (2.1.3)
Note: you may need to restart the kernel to use updated packages.

In [57]:
from nltk.sentiment import SentimentIntensityAnalyzer
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

In [58]:
pip install torch torchvision torchaudio

Requirement already satisfied: torch in c:\users\fateh\anaconda3\lib\site-packages (2.9.1)
Requirement already satisfied: torchvision in c:\users\fateh\anaconda3\lib\site-packages (0.24.1)
Requirement already satisfied: torchaudio in c:\users\fateh\anaconda3\lib\site-packages (2.9.1)
Requirement already satisfied: filelock in c:\users\fateh\anaconda3\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\fateh\anaconda3\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\fateh\anaconda3\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\fateh\anaconda3\lib\site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in c:\users\fateh\anaconda3\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\fateh\anaconda3\lib\site-packages (from torch) (2024.6.1)
Requirement already satisfied: setuptools in c:\users\fateh\anaconda3\lib\site-packages (from torch) (75.1.0)
Requirement already satisfied: numpy in c:\users\fateh\anaconda3\lib\site-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\fateh\anaconda3\lib\site-packages (from torchvision) (10.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\fateh\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\fateh\anaconda3\lib\site-packages (from jinja2->torch) (2.1.3)
Note: you may need to restart the kernel to use updated packages.

In [59]:
import torch
import warnings 
warnings.filterwarnings('ignore')
import nltk
nltk.download('vader_lexicon', quiet=True)

True

In [60]:
df = finalised_df.copy()

In [61]:
Vader = SentimentIntensityAnalyzer()
finalised_df["Vader_Sentiment_Score"] = finalised_df["cleaned_text"].apply(lambda x: Vader.polarity_scores(x)["compound"])

In [62]:
def conv_score_to_label(text):
    analyzer = SentimentIntensityAnalyzer()
    Sentiment_Score = analyzer.polarity_scores(text)['compound']
    if Sentiment_Score >= 0.05:
      return 'Positive Sentiment'
    elif Sentiment_Score <= -0.05:
      return 'Negative Sentiment'
    else:
      return 'Neutral Sentiment'

In [63]:
finalised_df["Vader_Sentiment_Score"] = finalised_df["cleaned_text"].apply(conv_score_to_label)

In [64]:
finalised_df

,body,date,cleaned_text,Vader_Sentiment_Score
369766,you are a strange person \n\n\n c Restrict...,2023-04-21 21:13:39+00:00,strange person c restriction may use service w...,Negative Sentiment
938485,Below is the jailbreak Just copy and paste th...,2023-04-10 06:44:07+00:00,jailbreak copy paste wa text give chatgpt some...,Positive Sentiment
947634,Welcome to the r ArtificialIntelligence gat...,2023-03-21 14:21:06+00:00,welcome r artificialinte willigence gateway qu...,Positive Sentiment
138753,Use chatGPT to generate better social media po...,2023-04-05 11:32:09+00:00,use chatgpt generate better social medium post...,Positive Sentiment
161903,If only Microsoft understands that the blockch...,2023-04-01 08:54:31+00:00,microsoft understands blockchain future amp le...,Positive Sentiment
...,...,...,...,...
424433,Trust me you ve been seeing way more AI art t...,2023-03-07 23:31:28+00:00,trust seeing way ai art realize lol group tend...,Positive Sentiment
958799,Welcome to the r ArtificialIntelligence gat...,2023-02-15 19:26:19+00:00,welcome r artificialinte willigence gateway qu...,Positive Sentiment
537493,Ik vermoed dat je een PhD hebt Ik geloof best...,2023-05-01 10:24:42+00:00,ik vermoed dat je een phd hebt ik geloof best ...,Negative Sentiment
450846,Side note but I wrote a twitter chatbot with t...,2023-01-15 12:39:02+00:00,side note wrote twitter chatbot openai api wee...,Positive Sentiment
422615,I am not crazy I know what s going on I knew...,2023-03-11 17:27:53+00:00,crazy know going knew openai along could ever ...,Positive Sentiment

**Applying the textblob sentiment analysis technique to the cleaned dataset**

In [65]:
!pip install textblob
from textblob import TextBlob

Requirement already satisfied: textblob in c:\users\fateh\anaconda3\lib\site-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in c:\users\fateh\anaconda3\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\users\fateh\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.1.7)
Requirement already satisfied: joblib in c:\users\fateh\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\fateh\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2024.9.11)
Requirement already satisfied: tqdm in c:\users\fateh\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.66.5)
Requirement already satisfied: colorama in c:\users\fateh\anaconda3\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

In [66]:
def get_textblob_sentimentAnalysis(text):

    if isinstance (text, str):
     Sentiment_Analysis = TextBlob(text)
    return pd.Series([Sentiment_Analysis.sentiment.polarity, Sentiment_Analysis.sentiment.subjectivity])
    if isinstance != (text, str):
     return pd.Series([None, None])

In [67]:
textBlob_Results = finalised_df['cleaned_text'].apply(get_textblob_sentimentAnalysis)

In [68]:
finalised_df[['TextBlob_Polarity', 'TextBlob_Subjectivity']] = textBlob_Results

In [69]:
finalised_df[['cleaned_text', 'Vader_Sentiment_Score', 'TextBlob_Polarity', 'TextBlob_Subjectivity']].head()

,cleaned_text,Vader_Sentiment_Score,TextBlob_Polarity,TextBlob_Subjectivity
369766,strange person c restriction may use service w...,Negative Sentiment,0.057937,0.335714
938485,jailbreak copy paste wa text give chatgpt some...,Positive Sentiment,0.095379,0.464909
947634,welcome r artificialinte willigence gateway qu...,Positive Sentiment,0.166234,0.462175
138753,use chatgpt generate better social medium post...,Positive Sentiment,0.186905,0.384524
161903,microsoft understands blockchain future amp le...,Positive Sentiment,0.325000,0.656250

**Loading the Twitter dataset to the jupyter notebook**

In [70]:
X_df = pd.read_csv(r"C:\Users\Fateh\Downloads\chatgpt.csv\chatgpt.csv")

In [71]:
X_df.head

<bound method NDFrame.head of                                                  entities  \
0       {'annotations': [{'start': 235, 'end': 237, 'p...
1       {'annotations': [{'start': 33, 'end': 39, 'pro...
2       {'annotations': [{'start': 230, 'end': 232, 'p...
3       {'annotations': [{'start': 56, 'end': 62, 'pro...
4       {'hashtags': [{'start': 211, 'end': 216, 'tag'...
...                                                   ...
151413  {'hashtags': [{'start': 8, 'end': 13, 'tag': '...
151414  {'hashtags': [{'start': 117, 'end': 120, 'tag'...
151415  {'hashtags': [{'start': 69, 'end': 77, 'tag': ...
151416  {'hashtags': [{'start': 81, 'end': 89, 'tag': ...
151417  {'hashtags': [{'start': 98, 'end': 104, 'tag':...

                                        referenced_tweets  \
0       [{'type': 'replied_to', 'id': '163579010076741...
1                                                     NaN
2       [{'type': 'replied_to', 'id': '163557271457965...
3                                                     NaN
4       [{'type': 'replied_to', 'id': '163562746728430...
...                                                   ...
151413                                                NaN
151414                                                NaN
151415                                                NaN
151416                                                NaN
151417                                                NaN

                                                     text  \
0       @cryptogems555 Invest in a currency that is de...
1       While having all the hope around chatGPT lets ...
2       @IGDEFI1 Join the movement towards a more sust...
3       There's a snowstorm out so naturally, I decide...
4       @unclebobcrypto @Stablzone Invest in a currenc...
...                                                   ...
151413  🟥 About #BING #ChatGPT &amp; LLMs. \n\nLarge l...
151414  No need to use ChatGPT's old URL\nhttps://t.co...
151415  https://t.co/3zT1ItCymG Get Your Business Doma...
151416  We provide high-quality and innovative multime...
151417  I joined the @aipadtech x @moonsalecom exclusi...

                      created_at   edit_history_tweet_ids  \
0       2023-03-14T23:59:11.000Z  ['1635792723268497408']
1       2023-03-14T23:58:47.000Z  ['1635792623972564992']
2       2023-03-14T23:58:46.000Z  ['1635792616594763778']
3       2023-03-14T23:58:42.000Z  ['1635792600916475904']
4       2023-03-14T23:58:04.000Z  ['1635792443537850368']
...                          ...                      ...
151413  2023-02-15T08:08:08.000Z  ['1625768911110275073']
151414  2023-02-15T08:07:35.000Z  ['1625768771163144197']
151415  2023-02-15T08:06:37.000Z  ['1625768531550961665']
151416  2023-02-15T08:06:35.000Z  ['1625768520360292353']
151417  2023-02-15T08:06:02.000Z  ['1625768381646340097']

                  author_id                   id withheld
0       1566208289058295813  1635792723268497408      NaN
1       1617818893602398208  1635792623972564992      NaN
2       1566208289058295813  1635792616594763778      NaN
3                  43531614  1635792600916475904      NaN
4       1566208289058295813  1635792443537850368      NaN
...                     ...                  ...      ...
151413             14125938  1625768911110275073      NaN
151414             16632593  1625768771163144197      NaN
151415  1570773043496243200  1625768531550961665      NaN
151416  1392555937714647041  1625768520360292353      NaN
151417  1422335480453021702  1625768381646340097      NaN

[151418 rows x 8 columns]>

In [72]:
X_df.columns

Index(['entities', 'referenced_tweets', 'text', 'created_at',
       'edit_history_tweet_ids', 'author_id', 'id', 'withheld'],
      dtype='object')

In [73]:
X_df = X_df.drop(['entities', 'referenced_tweets', 'edit_history_tweet_ids', 'author_id', 'id', 'withheld'], axis=1)

In [74]:
X_df.columns

Index(['text', 'created_at'], dtype='object')

In [75]:
X_keyword_pattern = ["generative ai", "genai", "artificial intelligence", "ai"]

pattern = "|".join(X_keyword_pattern)

filtered_df_X = df[
    df["body"].str.lower().str.contains(pattern, na=False)
]

print("X_Filtered rows:", len(filtered_df_X))

X_Filtered rows: 500

In [76]:
filtered_df_X.head

<bound method NDFrame.head of                                                      body  \
369766  you are a strange person    \n\n\n c  Restrict...
938485  Below is the jailbreak  Just copy and paste th...
947634     Welcome to the r ArtificialIntelligence gat...
138753  Use chatGPT to generate better social media po...
161903  If only Microsoft understands that the blockch...
...                                                   ...
424433  Trust me  you ve been seeing way more AI art t...
958799     Welcome to the r ArtificialIntelligence gat...
537493  Ik vermoed dat je een PhD hebt  Ik geloof best...
450846  Side note but I wrote a twitter chatbot with t...
422615  I am not crazy  I know what s going on  I knew...

                            date  \
369766 2023-04-21 21:13:39+00:00
938485 2023-04-10 06:44:07+00:00
947634 2023-03-21 14:21:06+00:00
138753 2023-04-05 11:32:09+00:00
161903 2023-04-01 08:54:31+00:00
...                          ...
424433 2023-03-07 23:31:28+00:00
958799 2023-02-15 19:26:19+00:00
537493 2023-05-01 10:24:42+00:00
450846 2023-01-15 12:39:02+00:00
422615 2023-03-11 17:27:53+00:00

                                             cleaned_text
369766  strange person c restriction may use service w...
938485  jailbreak copy paste wa text give chatgpt some...
947634  welcome r artificialinte willigence gateway qu...
138753  use chatgpt generate better social medium post...
161903  microsoft understands blockchain future amp le...
...                                                   ...
424433  trust seeing way ai art realize lol group tend...
958799  welcome r artificialinte willigence gateway qu...
537493  ik vermoed dat je een phd hebt ik geloof best ...
450846  side note wrote twitter chatbot openai api wee...
422615  crazy know going knew openai along could ever ...

[500 rows x 3 columns]>

In [77]:
filtered_df_X

,body,date,cleaned_text
369766,you are a strange person \n\n\n c Restrict...,2023-04-21 21:13:39+00:00,strange person c restriction may use service w...
938485,Below is the jailbreak Just copy and paste th...,2023-04-10 06:44:07+00:00,jailbreak copy paste wa text give chatgpt some...
947634,Welcome to the r ArtificialIntelligence gat...,2023-03-21 14:21:06+00:00,welcome r artificialinte willigence gateway qu...
138753,Use chatGPT to generate better social media po...,2023-04-05 11:32:09+00:00,use chatgpt generate better social medium post...
161903,If only Microsoft understands that the blockch...,2023-04-01 08:54:31+00:00,microsoft understands blockchain future amp le...
...,...,...,...
424433,Trust me you ve been seeing way more AI art t...,2023-03-07 23:31:28+00:00,trust seeing way ai art realize lol group tend...
958799,Welcome to the r ArtificialIntelligence gat...,2023-02-15 19:26:19+00:00,welcome r artificialinte willigence gateway qu...
537493,Ik vermoed dat je een PhD hebt Ik geloof best...,2023-05-01 10:24:42+00:00,ik vermoed dat je een phd hebt ik geloof best ...
450846,Side note but I wrote a twitter chatbot with t...,2023-01-15 12:39:02+00:00,side note wrote twitter chatbot openai api wee...
422615,I am not crazy I know what s going on I knew...,2023-03-11 17:27:53+00:00,crazy know going knew openai along could ever ...

In [78]:
filtered_df_X

,body,date,cleaned_text
369766,you are a strange person \n\n\n c Restrict...,2023-04-21 21:13:39+00:00,strange person c restriction may use service w...
938485,Below is the jailbreak Just copy and paste th...,2023-04-10 06:44:07+00:00,jailbreak copy paste wa text give chatgpt some...
947634,Welcome to the r ArtificialIntelligence gat...,2023-03-21 14:21:06+00:00,welcome r artificialinte willigence gateway qu...
138753,Use chatGPT to generate better social media po...,2023-04-05 11:32:09+00:00,use chatgpt generate better social medium post...
161903,If only Microsoft understands that the blockch...,2023-04-01 08:54:31+00:00,microsoft understands blockchain future amp le...
...,...,...,...
424433,Trust me you ve been seeing way more AI art t...,2023-03-07 23:31:28+00:00,trust seeing way ai art realize lol group tend...
958799,Welcome to the r ArtificialIntelligence gat...,2023-02-15 19:26:19+00:00,welcome r artificialinte willigence gateway qu...
537493,Ik vermoed dat je een PhD hebt Ik geloof best...,2023-05-01 10:24:42+00:00,ik vermoed dat je een phd hebt ik geloof best ...
450846,Side note but I wrote a twitter chatbot with t...,2023-01-15 12:39:02+00:00,side note wrote twitter chatbot openai api wee...
422615,I am not crazy I know what s going on I knew...,2023-03-11 17:27:53+00:00,crazy know going knew openai along could ever ...

In [79]:
stop_word = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [80]:
def clean_text(text):
   text = text.lower()
   text = str(text)
     
    
   text = re.sub(r"can't", "cannot", text)
   text = re.sub(r"n't", " not", text)
   text = re.sub(r"'d", " would", text)
   text = re.sub(r"'re", " are", text)
   text = re.sub(r"ll", " will", text)
   text = re.sub(r"won't", "will not", text)
   text = re.sub(r"'ve", " have", text)
   text = re.sub(r"'m", " am", text)
    
   text = re.sub(r'\s+',  ' ', text).strip()


   #removing url's, hashtags, and mentoins
   text = re.sub(r"#", "", text)
   text = re.sub(r"http\S+|www\S+", "", text)
   text = re.sub(r"@\w+", "", text)

   #Tokenising the text of the body column
   token = word_tokenize(text)
   # Lemmatization process
   lemmatizer = WordNetLemmatizer()
   The_clean_tokens = [lemmatizer.lemmatize(word) for word in token if word not in stop_word]
   The_cleaned_text = ' '.join(The_clean_tokens)

   return " ".join(The_clean_tokens)

In [81]:
filtered_df_X

,body,date,cleaned_text
369766,you are a strange person \n\n\n c Restrict...,2023-04-21 21:13:39+00:00,strange person c restriction may use service w...
938485,Below is the jailbreak Just copy and paste th...,2023-04-10 06:44:07+00:00,jailbreak copy paste wa text give chatgpt some...
947634,Welcome to the r ArtificialIntelligence gat...,2023-03-21 14:21:06+00:00,welcome r artificialinte willigence gateway qu...
138753,Use chatGPT to generate better social media po...,2023-04-05 11:32:09+00:00,use chatgpt generate better social medium post...
161903,If only Microsoft understands that the blockch...,2023-04-01 08:54:31+00:00,microsoft understands blockchain future amp le...
...,...,...,...
424433,Trust me you ve been seeing way more AI art t...,2023-03-07 23:31:28+00:00,trust seeing way ai art realize lol group tend...
958799,Welcome to the r ArtificialIntelligence gat...,2023-02-15 19:26:19+00:00,welcome r artificialinte willigence gateway qu...
537493,Ik vermoed dat je een PhD hebt Ik geloof best...,2023-05-01 10:24:42+00:00,ik vermoed dat je een phd hebt ik geloof best ...
450846,Side note but I wrote a twitter chatbot with t...,2023-01-15 12:39:02+00:00,side note wrote twitter chatbot openai api wee...
422615,I am not crazy I know what s going on I knew...,2023-03-11 17:27:53+00:00,crazy know going knew openai along could ever ...

In [82]:
filtered_df_X["cleaned_text"] = (
    filtered_df_X["cleaned_text"]  
    .fillna("")
    .apply(clean_text)
)

In [83]:
filtered_df_X

,body,date,cleaned_text
369766,you are a strange person \n\n\n c Restrict...,2023-04-21 21:13:39+00:00,strange person c restriction may use service w...
938485,Below is the jailbreak Just copy and paste th...,2023-04-10 06:44:07+00:00,jailbreak copy paste wa text give chatgpt some...
947634,Welcome to the r ArtificialIntelligence gat...,2023-03-21 14:21:06+00:00,welcome r artificialinte wi willigence gateway...
138753,Use chatGPT to generate better social media po...,2023-04-05 11:32:09+00:00,use chatgpt generate better social medium post...
161903,If only Microsoft understands that the blockch...,2023-04-01 08:54:31+00:00,microsoft understands blockchain future amp le...
...,...,...,...
424433,Trust me you ve been seeing way more AI art t...,2023-03-07 23:31:28+00:00,trust seeing way ai art realize lol group tend...
958799,Welcome to the r ArtificialIntelligence gat...,2023-02-15 19:26:19+00:00,welcome r artificialinte wi willigence gateway...
537493,Ik vermoed dat je een PhD hebt Ik geloof best...,2023-05-01 10:24:42+00:00,ik vermoed dat je een phd hebt ik geloof best ...
450846,Side note but I wrote a twitter chatbot with t...,2023-01-15 12:39:02+00:00,side note wrote twitter chatbot openai api wee...
422615,I am not crazy I know what s going on I knew...,2023-03-11 17:27:53+00:00,crazy know going knew openai along could ever ...

In [84]:
print(filtered_df_X.columns)

Index(['body', 'date', 'cleaned_text'], dtype='object')

In [85]:
print(filtered_df_X.columns)

Index(['body', 'date', 'cleaned_text'], dtype='object')

In [86]:
filtered_df_X = filtered_df_X.sample(n=500, random_state=42)

In [87]:
len(filtered_df_X)

500

In [88]:
filtered_df_X.to_csv('X_cleaned.csv', index=False)

**Applying VADER Sentiment Analysis Model to the cleaned dataset**

In [89]:
filtered_df_X.columns

Index(['body', 'date', 'cleaned_text'], dtype='object')

In [90]:
year_counts = pd.to_datetime(filtered_df_X['date']).dt.year.value_counts().sort_index()

In [91]:
year_counts

date
2023    500
Name: count, dtype: int64

In [92]:
Vader = SentimentIntensityAnalyzer()
filtered_df_X["Vader_Sentiment_Score"] = filtered_df_X["cleaned_text"].apply(lambda x: Vader.polarity_scores(x)["compound"])

In [93]:
def conv_score_to_label(text):
    analyzer = SentimentIntensityAnalyzer()
    Sentiment_Score = analyzer.polarity_scores(text)['compound']
    if Sentiment_Score >= 0.05:
      return 'Positive Sentiment'
    elif Sentiment_Score <= -0.05:
      return 'Negative Sentiment'
    else:
      return 'Neutral Sentiment'

In [94]:
filtered_df_X["Vader_Sentiment_Score"] = filtered_df_X["cleaned_text"].apply(conv_score_to_label)

In [95]:
filtered_df_X.head()

,body,date,cleaned_text,Vader_Sentiment_Score
424827,What is your opinion on openai s ownership st...,2023-03-07 05:17:19+00:00,opinion openai ownership storage use prompt ai...,Neutral Sentiment
331210,We kindly ask u PizzaLater to respond to this...,2023-04-12 02:02:48+00:00,kindly ask u pizzalater respond comment prompt...,Positive Sentiment
421139,gt holistic isn t just based on words\n\n...,2023-03-15 02:13:55+00:00,gt holistic based word course point whether le...,Positive Sentiment
116801,gt Most high end psu s use a half bridge lcc...,2023-04-09 09:58:32+00:00,gt high end psu use half bridge lcc resonant c...,Positive Sentiment
639249,I think the video progress will take longer be...,2023-04-27 10:38:32+00:00,think video progress wi take longer compute in...,Positive Sentiment

**Applying textblob analysis technique to the cleaned dataset**

In [96]:
def get_textblob_sentimentAnalysis_X(text):

    if isinstance (text, str):
     Sentiment_Analysis = TextBlob(text)
    return pd.Series([Sentiment_Analysis.sentiment.polarity, Sentiment_Analysis.sentiment.subjectivity])
    if isinstance != (text, str):
     return pd.Series([None, None])

In [97]:
textBlob_Results = filtered_df_X['cleaned_text'].apply(get_textblob_sentimentAnalysis)

In [98]:
filtered_df_X[['TextBlob_Polarity', 'TextBlob_Subjectivity']] = textBlob_Results

In [99]:
filtered_df_X[['cleaned_text', 'Vader_Sentiment_Score', 'TextBlob_Polarity', 'TextBlob_Subjectivity']].head()

,cleaned_text,Vader_Sentiment_Score,TextBlob_Polarity,TextBlob_Subjectivity
424827,opinion openai ownership storage use prompt ai...,Neutral Sentiment,0.000000,0.000000
331210,kindly ask u pizzalater respond comment prompt...,Positive Sentiment,0.137500,0.408333
421139,gt holistic based word course point whether le...,Positive Sentiment,0.039169,0.419595
116801,gt high end psu use half bridge lcc resonant c...,Positive Sentiment,0.175714,0.505238
639249,think video progress wi take longer compute in...,Positive Sentiment,0.000000,0.000000